# Apache Kafka & Event Streaming — lesson m06l01 — Dual Writes And Why They Lose Data
# https://learnsome.tech/courses/kafka-course/watch?lesson=m06l01
# © LearnSome.tech
FROM python:3.12-alpine
RUN pip install --no-cache-dir --quiet \
    kafka-python==2.2.15 "psycopg[binary]==3.2.3"
WORKDIR /app
COPY . /app
